import { walkBlocks } from '../core/ast.js';

const generators = {
  event_start: () => '',
  motion_move: (block) => `ctx.x += ${Number(block.fields.amount ?? 10)};`,
  motion_set_x: (block) => `ctx.x = ${Number(block.fields.value ?? 0)};`,
  looks_say: (block) => `ctx.say(${JSON.stringify(block.fields.text ?? '')});`,
};

export function generateJavaScript(project) {
  const lines = [
    '// Generated by MoBlock',
    'export function createGame(canvas) {',
    '  const ctx = { x: 0, y: 0, say: () => {} };'
  ];

  for (const scene of project.scenes) {
    walkBlocks(scene.scripts, (block) => {
      const generator = generators[block.type];
      if (generator) lines.push(`  ${generator(block)}`);
    });
  }

  lines.push('  return ctx;', '}');
  return lines.join('\n');
}
